name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          # we need full git history for article dates
          fetch-depth: 0

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.5

      # we are using this version in order to build vscode-textmate
      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install
        # at some point all npm needs to be in package.json
        run: |
          npm install
          npm install -g less@2.7
          npm install -g less-plugin-clean-css@1.5
          haxelib install CodeCookBook-neko.hxml --always --quiet
          haxelib install highlighting.hxml --always --quiet
          haxelib list
      
      - name: Check out gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: ./output
          fetch-depth: 0
    
      - name: Prepare output directory
        run:
          rm -r ./output/*

      - name: Generate website
        run: |
          haxe CodeCookBook-neko.hxml
          haxe highlighting.hxml

      - name: Deploy to gh-pages branch
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages from $GITHUB_SHA"
          git push
        working-directory: ./output
